default:
  image: node:latest

pages:
  script:
    - npm install typescript
    - npx tsc --build --verbose
    - rm fiveserver.config.js
    - mkdir public
    - cp *.{css,html,ico,js,png} public
    - gzip -k -6 public/*.{css,html,js}
  artifacts:
    paths:
      - public
  only:
    - main
