default:
  image: node:latest

pages:
  script:
    - rm *.js
    - rm *.config.ts
    - rm -rf playwright-tests
    - npm install typescript
    - npx tsc --build --verbose
    - mkdir public
    - cp *.{css,html,ico,js,png} public
    - mkdir public/src
    - cp src/*.js public/src
    - gzip -k -6 public/*.{css,html,js} public/src/*.js
  artifacts:
    paths:
      - public
  only:
    - main
