default:
  image: node:latest

stages:
  - test
  - compile
  - deploy

playwright:
  stage: test
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    paths:
      - playwright-report/
  only:
    - main

typescript:
  stage: compile
  script:
    - npm ci
    - npx tsc --build --force --verbose
  artifacts:
    paths:
      - src/*.js
  only:
    - main

pages:
  stage: deploy
  script:
    - rm *.config.js
    - mkdir public
    - cp *.{css,html,ico,js,png} public
    - mkdir public/src
    - cp src/*.js public/src
    - gzip -k -6 public/*.{css,html,js} public/src/*.js
  artifacts:
    paths:
      - public
  only:
    - main
