import { test, expect } from '../fixture/fixture-coverage'

test.describe('conversation languages', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto('/game')
    })

    test('produces text for every method in every language', async ({ page }) => {
        const texts = await page.evaluate(async () => {
            const { conversationLanguages } = await import('../../src/conversation-languages.js')
            return conversationLanguages.map(conversationLanguage => [
                conversationLanguage.welcome(),
                conversationLanguage.unitTestGameTitle(),
                conversationLanguage.slogan(),
                conversationLanguage.home(),
                conversationLanguage.settingsTitle(),
                conversationLanguage.changeLanguage(),
                conversationLanguage.changeProgrammingLanguage(),
                conversationLanguage.invitation(),
                conversationLanguage.level(1, 'Voting Age'),
                conversationLanguage.nextLevelButton('Level 1 - Voting Age'),
                conversationLanguage.playButton(),
                conversationLanguage.retryButton(),
                conversationLanguage.retryLevelButton('Level 1 - Voting Age'),
                conversationLanguage.lockedButton(),
                conversationLanguage.allLevels(),
                conversationLanguage.closeTab(),
                conversationLanguage.unitTestsTitle(),
                conversationLanguage.addUnitTestButton(),
                conversationLanguage.submitUnitTestsButton(),
                conversationLanguage.unitTestNotAdded(),
                conversationLanguage.tooManyUnitTests(1, 1),
                conversationLanguage.tooManyUnitTests(2, 2),
                conversationLanguage.readSpecification(),
                conversationLanguage.improveCurrentFunction(),
                conversationLanguage.submitUnitTests(),
                conversationLanguage.specificationTitle('Voting Age'),
                conversationLanguage.currentFunctionTitle(),
                conversationLanguage.differenceTitle(),
                conversationLanguage.currentFunctionNotImproved(),
                conversationLanguage.hint(),
                conversationLanguage.currentFunctionImproved(1),
                conversationLanguage.currentFunctionImproved(2),
                conversationLanguage.invalidUnitTest(),
                conversationLanguage.moreUnitTests(1),
                conversationLanguage.moreUnitTests(2),
                conversationLanguage.currentFunctionCorrect(),
                conversationLanguage.levelOverviewTitle(),
                conversationLanguage.batteryLevelSpecification(),
                conversationLanguage.wrongAction(),
                conversationLanguage.addBatteryLevel20(),
                conversationLanguage.addBatteryLevel19(),
                conversationLanguage.submitUnitTestsFirst(),
                conversationLanguage.addBatteryLevel21(),
                conversationLanguage.submitUnitTestsSecond(),
                conversationLanguage.addBatteryLevel18(),
                conversationLanguage.submitUnitTestsThird(),
                conversationLanguage.windScaleSpecification(),
                conversationLanguage.fizzBuzzSpecification(),
                conversationLanguage.leapYearSpecification(),
                conversationLanguage.speedDisplaySpecification(),
                conversationLanguage.triangleTypeSpecification(),
                conversationLanguage.votingAgeSpecification(),
                conversationLanguage.reviewSpecification(),
                conversationLanguage.discountSpecification(),
                conversationLanguage.parkingFeeSpecification(),
                conversationLanguage.or(),
                conversationLanguage.parameterLabel('year'),
                conversationLanguage.returnValueLabel('isLeapYear(year)'),
                conversationLanguage.indexMetaDescription(),
                conversationLanguage.indexPageTitle(),
                conversationLanguage.navHowItWorks(),
                conversationLanguage.navLevels(),
                conversationLanguage.navWhyItWorks(),
                conversationLanguage.navPlayNow(),
                conversationLanguage.heroTitleLine1Start(),
                conversationLanguage.heroTitleLine1Gradient(),
                conversationLanguage.heroTitleLine2Start(),
                conversationLanguage.heroTitleLine2Gradient(),
                conversationLanguage.heroSubtitle(),
                conversationLanguage.heroCtaPrimary(),
                conversationLanguage.heroCtaSecondary(),
                conversationLanguage.humanWantsToAddUnitTest(),
                conversationLanguage.heroCommentThisIsYou(),
                conversationLanguage.heroCommentFirstUnitTest(),
                conversationLanguage.heroCommentThisIsTheAiBot(),
                conversationLanguage.heroCommentFirstFunctionPasses(),
                conversationLanguage.heroCommentFirstVerdict(),
                conversationLanguage.heroCommentThisIsYouAgain(),
                conversationLanguage.heroCommentSecondUnitTest(),
                conversationLanguage.heroCommentThisIsTheAiBotAgain(),
                conversationLanguage.heroCommentSecondFunctionPasses(),
                conversationLanguage.heroCommentSecondVerdict(),
                conversationLanguage.howItWorksTitle(),
                conversationLanguage.howItWorksSubtitle(),
                conversationLanguage.howItWorksStep1Title(),
                conversationLanguage.howItWorksStep1Desc(),
                conversationLanguage.howItWorksStep2Title(),
                conversationLanguage.howItWorksStep2Desc(),
                conversationLanguage.howItWorksStep3Title(),
                conversationLanguage.howItWorksStep3Desc(),
                conversationLanguage.howItWorksStep4Title(),
                conversationLanguage.howItWorksStep4Desc(),
                conversationLanguage.whyItWorksTitle(),
                conversationLanguage.whyItWorksSubtitle(),
                conversationLanguage.whyItWorksItem1Title(),
                conversationLanguage.whyItWorksItem1Desc(),
                conversationLanguage.whyItWorksItem2Title(),
                conversationLanguage.whyItWorksItem2Desc(),
                conversationLanguage.whyItWorksItem3Title(),
                conversationLanguage.whyItWorksItem3Desc(),
                conversationLanguage.whyItWorksItem4Title(),
                conversationLanguage.languagesList(),
                conversationLanguage.whyItWorksItem5Title(),
                conversationLanguage.programmingLanguagesList(),
                conversationLanguage.whyItWorksItem6Title(),
                conversationLanguage.whyItWorksItem6Desc(),
                conversationLanguage.levelsTitle(),
                conversationLanguage.levelsSubtitle(),
                conversationLanguage.levelsDifficultyEasy(),
                conversationLanguage.levelsDifficultyMedium(),
                conversationLanguage.levelsDifficultyHard(),
                conversationLanguage.levelBlurb0(),
                conversationLanguage.levelBlurb1(),
                conversationLanguage.levelBlurb2(),
                conversationLanguage.levelBlurb3(),
                conversationLanguage.levelBlurb4(),
                conversationLanguage.levelBlurb5(),
                conversationLanguage.levelBlurb6(),
                conversationLanguage.levelBlurb7(),
                conversationLanguage.levelBlurb8(),
                conversationLanguage.levelBlurb9(),
                conversationLanguage.faqTitle(),
                conversationLanguage.faqSubtitle(),
                conversationLanguage.faqQuestion1(),
                conversationLanguage.faqAnswer1(),
                conversationLanguage.faqQuestion2(),
                conversationLanguage.faqQuestion3(),
                conversationLanguage.faqQuestion4(),
                conversationLanguage.faqAnswer4(),
                conversationLanguage.faqQuestion5(),
                conversationLanguage.faqAnswer5(),
                conversationLanguage.faqQuestion6(),
                conversationLanguage.faqAnswer6(),
                conversationLanguage.faqQuestion7(),
                conversationLanguage.faqAnswer7(),
                conversationLanguage.faqQuestion8(),
                conversationLanguage.faqAnswer8(),
                conversationLanguage.ctaTitle(),
                conversationLanguage.ctaSubtitle(),
                conversationLanguage.ctaButton(),
                conversationLanguage.footerContact(),
            ])
        })
        for (const text of texts)
            expect(text).not.toBe('')
    })
})
